// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTAa5SbPAfGnP69UwUbMh_WKrAlAPzy38',
    appId: '1:525423620937:web:b541197017b72517696098',
    messagingSenderId: '525423620937',
    projectId: 'shopapp-4dd39',
    authDomain: 'shopapp-4dd39.firebaseapp.com',
    storageBucket: 'shopapp-4dd39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3d7VZ-bpUdx6c4T6QG1rDEm6oNUH84U',
    appId: '1:525423620937:android:56e377c5801c8a27696098',
    messagingSenderId: '525423620937',
    projectId: 'shopapp-4dd39',
    storageBucket: 'shopapp-4dd39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXGUq-eucksoCMO3ioDqzzCaArHgYwjs',
    appId: '1:525423620937:ios:01e1d95583931355696098',
    messagingSenderId: '525423620937',
    projectId: 'shopapp-4dd39',
    storageBucket: 'shopapp-4dd39.appspot.com',
    iosClientId: '525423620937-51hiuknlrgot9r0jjcse7s2530q19nfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXGUq-eucksoCMO3ioDqzzCaArHgYwjs',
    appId: '1:525423620937:ios:01e1d95583931355696098',
    messagingSenderId: '525423620937',
    projectId: 'shopapp-4dd39',
    storageBucket: 'shopapp-4dd39.appspot.com',
    iosClientId: '525423620937-51hiuknlrgot9r0jjcse7s2530q19nfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
